Story/wics 6
diging/women-in-computer-science pull request #14
Opened 2021-04-28 20:22 UTC by shahsmit49

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

After logging in, there should be a page that lists all texts(with pagination). When the user adds a new text, they would have to select a concept (similar to when importing a new concept), add a title for the text, an author, and then add the text in markdown.

When saving a timestamp should be recorded and who added the text.

From the list of texts, the text should be editable and deletable.
  
## Anything else the reviewer needs to know?

In pom.xml I have only added Javers, Mockito, JUnit dependency but it was causing the spacing issue so I have to reformat the file. So you can ignore the rest of the changes shown here

2021-04-29 14:45 UTC, jdamerow requested changes

2021-04-29 14:45 UTC, jdamerow commented on wic/pom.xml
> +            <artifactId>eclipselink</artifactId>
what is this used for?

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/core/service/impl/ConceptTextService.java
> +    public List<ConceptText> findAll(Integer page, Integer itemsPerPage) {
there should be a sort parameter as well (field and sort order)

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/core/repository/ConceptTextDatabaseRepository.java
> +public interface ConceptTextDatabaseRepository extends PagingAndSortingRepository<ConceptText, Long> {
Let's just call it `ConceptTextRepository`. No need to make it overly long.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/core/service/impl/ConceptTextService.java
> +    private ConceptTextDatabaseRepository conceptTextDatabaseConnection;
jsut call this `repo` or `repository`.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/core/service/impl/ConceptTextService.java
> +        return conceptTextUpdate;
I don't think you need to update the object like this. As long as it has the same id, you should be able to just store the passed concept text object.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/core/service/impl/ConceptTextService.java
> +        return conceptTextDatabaseConnection.findById(id).get();
I'm fairly certain that `get` will throw an exception if there is no found object.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/web/conceptText/AddConceptTextController.java
> +package edu.asu.diging.wic.web.conceptText;
Let's call the new package just `texts`

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/java/edu/asu/diging/wic/web/conceptText/ShowConceptTextController.java
> +        List<ConceptText> allConceptText = conceptTextService.findAll(page, itemsPerPage);
should be plural since you have a list

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/resources/config.properties
> +hibernate.show_sql=true
undo this please. we don't need all sql queries logged in production

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/resources/config.properties
> +itemsPerPage = 5
let's make this 15

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/conceptText/addConceptText.jsp
> +<form:form method='POST' action="/wic/admin/text/add" modelAttribute="conceptTextFormData" onsubmit="return verifyNonEmpty()">
`wic` cannot be hard-coded. There is no guarantee the app will always be deployed as `wic`.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/conceptText/addConceptText.jsp
> +<form:form method='POST' action="/wic/admin/text/add" modelAttribute="conceptTextFormData" onsubmit="return verifyNonEmpty()">
(e.g. in the staging instance it's not)

2021-04-29 14:45 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/conceptText/editConceptText.jsp
> +<form:form action="/wic/admin/text/${conceptTextFormData.id}/edit" modelAttribute="conceptTextFormData" method='POST'>
see above

2021-04-29 14:45 UTC, jdamerow commented on wic/src/test/java/edu/asu/diging/wic/core/service/impl/ConceptTextServiceTest.java
> +    public void testAddText() {
please read our test code guidelines and follow them

2021-04-29 14:45 UTC, jdamerow commented on wic/src/test/java/edu/asu/diging/wic/core/service/impl/ConceptTextServiceTest.java
> +        verify(conceptTextDatabaseConnection).findAll(any(Pageable.class));
that doesn't really need to be test, but you do need to test if you get the objects you expect to get.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/test/java/edu/asu/diging/wic/core/service/impl/ConceptTextServiceTest.java
> +    }
also needs test case for when a non-existing id is passed.

2021-04-29 14:45 UTC, jdamerow commented on wic/src/test/java/edu/asu/diging/wic/core/service/impl/ConceptTextServiceTest.java
> +        verify(conceptTextDatabaseConnection,times(1)).count();
that doesn't really matter. if the total count is found in a different way the outcome can still be correct.

2021-09-01 19:03 UTC, MaulikLim commented
Addressed review comments.
The text is already being displayed on the list page. I have limited it to display only a single line instead of the entire text.

2021-09-01 19:20 UTC, jdamerow commented
- the markdown is still not rendered on the list page:
![image](https://user-images.githubusercontent.com/8881141/131730803-08cf2358-11d6-44bb-8cf1-47832e507314.png)

2021-09-08 18:53 UTC, MaulikLim commented
Handled the markdown text rendering from back-end

2021-09-08 19:53 UTC, jdamerow requested changes

2021-09-08 19:53 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/texts/showConceptText.jsp
> +	var url = "/wic/admin/text/"+deleteValue+"/delete?${_csrf.parameterName}=${_csrf.token}";
"wic" is not always the name of the deployed application, it can't be hard-coded.

2021-09-08 19:53 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/texts/showConceptText.jsp
> +		},
there hsould be a success message if successful.

2021-09-14 18:58 UTC, jdamerow requested changes
Just this little bit of clean up and it should be good to go.

2021-09-14 18:58 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/texts/addConceptText.jsp
> +	$("#confirmModal").modal('show');
does this modal exist?

2021-09-14 18:58 UTC, jdamerow commented on wic/src/main/webapp/WEB-INF/views/admin/texts/addConceptText.jsp
> +</script>
indentation needs some fixing

2021-09-15 19:55 UTC, jdamerow commented
Make it so, Jenkins.

2021-09-15 20:02 UTC, merged